name: Auto Create Release PR

on:
  push:
    branches:
      - develop

jobs:
  create-release-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby 3.1
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Create a release pull request
        id: create-pr
        run: |
          gem install -N git-pr-release
        env:
          GIT_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR_RELEASE_BRANCH_PRODUCTION: prod
          GIT_PR_RELEASE_BRANCH_STAGING: develop
          GIT_PR_RELEASE_LABELS: release
          GIT_PR_RELEASE_TEMPLATE: './.github/dev2prod-pr-template.erb'
      - name: Display PR Link
        run: |
          echo "The PR Link is: ${{ steps.create-pr.outputs.pr_url }}"  # create-prステップの出力を参照

