name: Auto Create Release PR

on:
  push:
    branches:
      - develop

jobs:
  create-release-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby 3.1
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Create a release pull request
        id: create-pr
        run: |
          gem install -N git-pr-release
          git-pr-release 1>output.txt 2>&1
          cat output.txt  # output.txtの内容をログに出力します
        env:
          GIT_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR_RELEASE_BRANCH_PRODUCTION: prod
          GIT_PR_RELEASE_BRANCH_STAGING: develop
          GIT_PR_RELEASE_LABELS: release
      - name: Display PR Link  # 新しいステップを追加して、作成されたPRのリンクを表示します
        run: |
          echo "The PR Link is: ${{ steps.create-pr.outputs.pr_url }}"  # create-prステップの出力を参照

