on:
  push:
    branches:
      - 'develop'
      - 'prod'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled

name: CI

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Code
        uses: actions/checkout@v3
      - name: Check diff between gofmt and code
        run: diff <(gofmt -d .) <(echo -n)
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Code
        uses: actions/checkout@v3
      - name: Go vet
        run: go vet -x ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52.2
          skip-pkg-cache: true
          skip-build-cache: true
  trigger-release-pr:  # 新しいジョブを追加
    needs: [format, lint]  # formatとlintジョブが成功した場合にのみ実行
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Release PR Workflow
        run: |
          curl -XPOST -u "${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{"event_type": "create_release_pr"}'