name: Generate and Deploy Markdown to GitHub Pages

on:
  push:
    branches: ["develop"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ステップ: Markdownファイルの生成
      - name: Generate Markdown File
        run: |
          echo "# Hello World" > hello-world.md
          echo "This is a generated Markdown file." >> hello-world.md

      # GitHub Pagesのセットアップ
      - name: Setup Pages
        uses: actions/configure-pages@v4

      # アーティファクトのアップロード
      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'

      # GitHub Pagesへのデプロイ
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
